### ISSUE TITLE
Trace errors running "vanilla" Swordfish emulator

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-API-Emulator#39]
On install of a clean emulator, these trace errors are showing up on simple GETs:

Traceback (most recent call last):
  File "emulator.py", line 279, in get_configuration
    config = obj.get_resource(path)
  File "/cygdrive/C/Users/rahlvers/Github/Redfish-Interface-Emulator/api_emulato         r/resource_manager.py", line 405, in get_resource
    obj = self.resource_dictionary.get_resource(path)
  File "/cygdrive/C/Users/rahlvers/Github/Redfish-Interface-Emulator/api_emulato         r/resource_dictionary.py", line 19, in get_resource
    obj = resdict[path].configuration
KeyError: 'StorageServices/'
Traceback (most recent call last):
  File "emulator.py", line 279, in get_configuration
    config = obj.get_resource(path)
  File "/cygdrive/C/Users/rahlvers/Github/Redfish-Interface-Emulator/api_emulato         r/resource_manager.py", line 405, in get_resource
    obj = self.resource_dictionary.get_resource(path)
  File "/cygdrive/C/Users/rahlvers/Github/Redfish-Interface-Emulator/api_emulato         r/resource_dictionary.py", line 19, in get_resource
    obj = resdict[path].configuration
KeyError: 'StorageServices/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emulator.py", line 180, in get
    config = self.get_configuration(resource_manager, path)
  File "emulator.py", line 282, in get_configuration
    raise PathError("Resource not found: " + str(e.message))
AttributeError: 'KeyError' object has no attribute 'message'
[2018-06-27 14:59:35,416] ERROR in app: Exception on /redfish/v1/StorageServices         / [GET]
Traceback (most recent call last):
  File "emulator.py", line 279, in get_configuration
    config = obj.get_resource(path)
  File "/cygdrive/C/Users/rahlvers/Github/Redfish-Interface-Emulator/api_emulato         r/resource_manager.py", line 405, in get_resource
    obj = self.resource_dictionary.get_resource(path)
  File "/cygdrive/C/Users/rahlvers/Github/Redfish-Interface-Emulator/api_emulato         r/resource_dictionary.py", line 19, in get_resource
    obj = resdict[path].configuration
KeyError: 'StorageServices/'

**Comment by rahlvers** [comment]
Looking at the traces, these are all issues with parsing the trailing "/" values.

**Comment by ddeel** [comment]
I've just started running the latest Swordfish API Emulator code (Swordfish-26thjune branch) with the latest Redfish Interface Emulator code (master branch), and it seems to be working. I am not having trouble accessing Redfish and Swordfish resources with GETs, as long as the trailing "/" is not present.

The Redfish Interface Emulator does not currently tolerate a trailing "/" on URLs unless the URL is for the service root (/redfish/v1/). The errors seen when a trailing "/" is present are exactly like the ones you are seeing.

If you are seeing this problem using Chrome, then be aware that Chrome's URL cache can interact badly with the emulator on this, and it can even affect Restlet Client behavior. The only way to fix the problem is to open Developer Tools on the Chrome page (Ctrl-Shift I) and then click-and-hold on the page refresh button until you can select the "Empty Cache and Hard Reload" option. After that, Chrome should have "forgotten" that it wants to add a trailing "/" to the URLs you are working with. (Learned this the hard way a few months ago, and it was not fun.)

**Comment by rahlvers** [comment]
Closed - not an issue with current master.
